---
- name: Clone repo branch
  git:
    repo: '{{ beacon_node_repo_url }}'
    version: '{{ beacon_node_repo_branch }}'
    dest: '{{ beacon_node_repo_path }}'
    force: true
    update: true
  become_user: '{{ beacon_node_user }}'

- name: Create build script
  template:
    src: 'build.sh.j2'
    dest: '{{ beacon_node_build_script_path }}'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0775

- name: Create launchd config file for builds
  template:
    src: 'launchd-build.plist.j2'
    dest: '{{ beacon_node_build_launchd_path }}'

- name: Reload launchd job definition
  community.general.launchd:
    name: 'status.{{ beacon_node_service_name }}-build'
    state: restarted
