---
- name: Clone repo
  git:
    repo: '{{ beacon_node_repo_url }}'
    version: '{{ beacon_node_repo_branch }}'
    dest: '{{ beacon_node_repo_path }}'
    force: true
    update: true
  become_user: '{{ beacon_node_user }}'

- name: Create launchd config file for scheduled builds
  template:
    src: launchd-build.plist.j2
    dest: '{{ beacon_node_build_launchd_path }}'

- name: Load launchd config into system
  community.general.launchd:
    name: '{{ beacon_node_build_launchd_service_name }}'
    state: reloaded

- name: Check if node binary exists
  stat:
    path: '{{ beacon_node_repo_path }}/build/nimbus_beacon_node'

- name: Start new node binary build
  community.general.launchd:
    name: '{{ beacon_node_build_launchd_service_name }}'
    state: started

- name: Wait for build to finish (SLOW)
  wait_for:
    path: '{{ beacon_node_repo_path }}/build/nimbus_beacon_node'
    timeout: 600 # 10min
