---
- name: Create service directory
  file:
    path:  '{{ beacon_node_service_path }}'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    state: directory
    mode:  0750

- name: Create data directory
  file:
    path:  '{{ beacon_node_data_path }}'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    state: directory
    # WARNING: Node needs these permissions to start.
    mode:  0700

- name: Create netkey file (optional)
  copy:
    dest:    '{{ beacon_node_netkey_path }}'
    content: '{{ beacon_node_netkey }}'
    owner:   '{{ beacon_node_user }}'
    group:   '{{ beacon_node_group }}'
    mode:    0600
  when: beacon_node_netkey is defined

- name: Create JWT secret file (optional)
  when: beacon_node_web3_jwt_secret is defined
  copy:
    dest:    '{{ beacon_node_web3_jwt_secret_path }}'
    content: '{{ beacon_node_web3_jwt_secret }}'
    group:   '{{ beacon_node_group }}'
