---
- name: Install logrotate via nix profile
  command: nix profile install nixpkgs#logrotate
  register: nix_install
  changed_when: "'installing' in nix_install.stderr"
  failed_when: nix_install.rc != 0 and 'already installed' not in nix_install.stderr

- name: Get logrotate binary path
  command: which logrotate
  register: logrotate_which
  changed_when: false

- name: Create logrotate directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    mode: '0755'
  with_items:
    - '/var/lib/logrotate'
    - '/etc/logrotate.d/'

- name: Create main logrotate config
  copy:
    content: |
      include /etc/logrotate.d
    dest: '/etc/logrotate.conf'
    owner: root
    mode: '0644'

- name: Create logrotate config for beacon node
  template:
    src: logrotate.conf.j2
    dest: '{{ beacon_node_logrotate_config_path }}'
    owner: root
    mode: 0644

# logrotate will fail to start if configs are not owned by root
- name: Make sure logrotate.conf is owned by root
  file:
    path: '{{ beacon_node_logrotate_main_config }}'
    owner: root

- name: Create launchd config for logrotate
  template:
    src: launchd-logrotate.plist.j2
    dest: '/Library/LaunchDaemons/{{ beacon_node_logrotate_service_name }}.plist'
    owner: root
    mode: '0644'

- name: Reload launchd config
  community.general.launchd:
    name: '{{ beacon_node_logrotate_service_name }}'
    state: reloaded
