---
- name: Install logrotate
  homebrew:
    name: logrotate
  become: false

# the homebrew package comes with a default launchd config that runs daily
# we overwrite it with one that runs hourly
- name: Create launchd config for logrotate
  template:
    src: launchd-logrotate.plist.j2
    dest: '/Library/LaunchDaemons/{{ beacon_node_logrotate_service_name }}.plist'
    owner: root
    mode: 0644

# logrotate needs to write its state file to /opt/homebrew/var/lib
# homebrew doesn't create this directory automatically
- name: Create logrotate state file directory
  file:
    path: '{{ homebrew_path }}/var/lib'
    state: directory
  become: false

- name: Create logrotate config for beacon node
  template:
    src: logrotate.conf.j2
    dest: '{{ beacon_node_logrotate_config_path }}'
    owner: root
    mode: 0644

# logrotate will fail to start if configs are not owned by root
- name: Make sure logrotate.conf is owned by root
  file:
    path: '{{ beacon_node_logrotate_main_config }}'
    owner: root

- name: Reload launchd config
  community.general.launchd:
    name: '{{ beacon_node_logrotate_service_name }}'
    state: reloaded
