---
- name: Install logrotate
  homebrew:
    name: logrotate
  become: false

# logrotate needs to write its state file to /opt/homebrew/var/lib
# homebrew doesn't create this directory automatically
- name: Create logrotate state file directory
  file:
    path: '{{ homebrew_path }}/var/lib'
    state: directory
  become: false

- name: Create logrotate config for beacon node
  template:
    src: logrotate.conf.j2
    dest: '{{ homebrew_path }}/etc/logrotate.d/{{ beacon_node_service_name }}.conf'
    owner: root
    mode: 0644

# logrotate will fail to start if configs are not owned by root
- name: Make sure logrotate.conf is owned by root
  file:
    path: '{{ homebrew_path }}/etc/logrotate.conf'
    owner: root

- name: Check if launchd config file already exists
  stat:
    path: '~/Library/LaunchAgents/homebrew.mxcl.logrotate.plist'
  register: logrotate_stat_plist
  become: false

# if the launch agent config already exists, calling "brew services start" will error
- name: Enable logrotate service to start on login
  command: '{{ homebrew_path }}/bin/brew services start logrotate'
  when:
    - not logrotate_stat_plist.stat.exists
  become: false
