# todo: brew install cmake

- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0750
  with_items:
    - '{{ beacon_node_data_path }}'

- name: Create user for beacon node builds
  user:
    name: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'

- name: Set disable rebase as merge strategy
  git_config:
    scope: 'global'
    name: 'pull.rebase'
    value: 'false'
  become_user: '{{ beacon_node_user }}'

- name: Clone repo branch
  git:
    repo: '{{ beacon_node_repo_url }}'
    version: '{{ beacon_node_repo_branch }}'
    dest: '{{ beacon_node_repo_path }}'
    force: true
    update: true
  become_user: '{{ beacon_node_user }}'

- name: Create build script
  template:
    src: 'build.sh.j2'
    dest: '{{ beacon_node_build_script_path }}'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0775
