- name: Create user for beacon node builds
  user:
    name: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    shell: '/bin/zsh'
    uid: 8000

- name: Copy .zshrc file for beacon node user
  copy:
    src: 'zshrc'
    dest: '/Users/{{ beacon_node_user }}/.zshrc'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0644

- name: Sudoers file for login as nimbus user
  template:
    src: 'nimbus_sudoers.j2'
    dest: '/etc/sudoers.d/81-nimbus-login'
    mode: 0440

- name: Create directories
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0750
  with_items:
    - '{{ beacon_node_data_path }}'

- name: Set disable rebase as merge strategy
  git_config:
    scope: 'global'
    name: 'pull.rebase'
    value: 'false'
  become_user: '{{ beacon_node_user }}'

- name: Clone repo branch
  git:
    repo: '{{ beacon_node_repo_url }}'
    version: '{{ beacon_node_repo_branch }}'
    dest: '{{ beacon_node_repo_path }}'
    force: true
    update: true
  become_user: '{{ beacon_node_user }}'

- name: Create build script
  template:
    src: 'build.sh.j2'
    dest: '{{ beacon_node_build_script_path }}'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0775

- name: Create build script launchd job definition
  template:
    src: 'launchd.plist.j2'
    dest: '{{ beacon_node_build_launchd_path }}'

- name: Reload launchd job definition
  community.general.launchd:
    name: com.status.beacon-node-build-unstable
    state: restarted
