---
- name: Create log directory for beacon node
  file:
    path: '{{ beacon_node_log_folder }}'
    state: directory
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0755

- name: Create beacon node launchd config file
  template:
    src: launchd.plist.j2
    dest: '{{ beacon_node_launchd_config_path }}'
  register: beacon_node_config_result

- name: Restart beacon node
  community.general.launchd:
    name: '{{ beacon_node_launchd_service_name }}'
    state: '{{ beacon_node_config_result.changed | ternary("restarted", "started") }}'
