---
- name: Create log directory
  file:
    path: '{{ beacon_node_log_folder }}'
    state: directory
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'

- name: Create launchd config directory
  file:
    path: '{{ beacon_node_launchd_config_folder }}'
    state: directory
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'

- name: Create beacon node launchd config file
  template:
    src: 'launchd.plist.j2'
    dest: '{{ beacon_node_launchd_config_path }}'

- name: Reload beacon node launchd config
  community.general.launchd:
    name: 'status.{{ beacon_node_service_name }}'
    state: reloaded
