---
- name: Create log directory
  file:
    path: '{{ beacon_node_log_folder }}'
    state: directory
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'

# newsyslog runs every 30 minutes
- name: Setup log rotation
  template:
    src: newsyslog.conf.j2
    dest: '/etc/newsyslog.d/{{ beacon_node_service_name }}.conf'
    mode: 0644

- name: Create beacon node launchd config file
  template:
    src: 'launchd.plist.j2'
    dest: '{{ beacon_node_launchd_config_path }}'

- name: Reload beacon node launchd config
  community.general.launchd:
    name: 'status.{{ beacon_node_service_name }}'
    state: reloaded
