---
- name: Create user for beacon node builds
  user:
    name: '{{ beacon_node_user }}'
    uid: '{{ beacon_node_uid }}'
    group: '{{ beacon_node_group }}'
    shell: '/bin/zsh'

- name: Copy .zshrc file for beacon node user
  copy:
    src: 'zshrc'
    dest: '{{ beacon_node_user_path }}/.zshrc'
    owner: '{{ beacon_node_user }}'
    group: '{{ beacon_node_group }}'
    mode: 0644

- name: Create sudoers file for nimbus user
  template:
    src: 'nimbus_sudoers.j2'
    dest: '/etc/sudoers.d/81-nimbus'
    mode: 0440

- name: Set disable rebase as merge strategy
  git_config:
    scope: 'global'
    name: 'pull.rebase'
    value: 'false'
  become_user: '{{ beacon_node_user }}'
